version: '3.1'

services:

  db:
    image: postgres
    restart: always
    volumes:
      - ${HOME}/psqldata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DESIGN: pepa-linha
    ports:
      - 8088:8080
    depends_on: 
      - db
